# Generated by Django 5.0.4 on 2024-04-17 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Employee', '0003_department_employee_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='department',
        ),
    ]
