# Generated by Django 5.0.4 on 2024-04-17 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Employee', '0005_employee_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='city',
            field=models.CharField(choices=[('Riyadh', 'Riyadh'), ('Abha', 'Abha'), ('Al Bahah', 'Al Bahah'), ('Dammam', 'Dammam'), ('Jeddah', 'Jeddah'), ('Jizan', 'Jizan'), ('Mecca', 'Mecca')], max_length=100),
        ),
    ]
