# Generated by Django 5.0.4 on 2024-04-18 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Employee', '0006_alter_contact_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='joined_date',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
    ]
