# Generated by Django 5.0.4 on 2024-04-24 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Employee', '0016_department_create_date_alter_employee_department'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='joined_date',
            new_name='creation_date',
        ),
        migrations.AddField(
            model_name='contact',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='employee',
            name='birth_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=20),
        ),
        migrations.AlterField(
            model_name='employee',
            name='salary',
            field=models.CharField(choices=[('5000', '5000'), ('8000', '8000'), ('10.000', '10.000'), ('12.000', '12.000'), ('15.000', '15.000')], max_length=100),
        ),
    ]
