# Generated by Django 5.0.4 on 2024-04-24 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Employee', '0017_rename_joined_date_employee_creation_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
