# Generated by Django 5.0.4 on 2024-04-27 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Employee', '0018_alter_contact_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_department',
            field=models.BooleanField(default=False),
        ),
    ]
