# Generated by Django 5.0.4 on 2024-04-27 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Employee', '0019_employee_is_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='join_department_date',
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
    ]
