# Generated by Django 5.0.4 on 2024-04-27 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Employee', '0020_employee_join_department_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='join_department_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
