# Generated by Django 5.0.4 on 2024-05-01 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Employee', '0022_compensation_employee_compensations'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_compensation',
            field=models.BooleanField(db_column='is Compensations', default=False),
        ),
        migrations.AlterField(
            model_name='employee',
            name='is_department',
            field=models.BooleanField(db_column='is Department', default=False),
        ),
    ]
