# Generated by Django 5.0.4 on 2024-05-01 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Employee', '0023_employee_is_compensation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='compensation',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='compensation',
            name='reward_price',
            field=models.IntegerField(default=500),
        ),
    ]
